{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcmpc",
    "version": "v0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-v0.1.0.aar",
          "url": "abcmpc-v0.1.0.aar",
          "size": 18696378,
          "sha512": "c801601ad78159901507868a467e310da9ea4cf377f2ed920c21dd6bd13907866dc150807524541cb8a17e80573cb266d9a6e0df1aeff87ab3bfce29b6b89566",
          "sha256": "8bf9e9843c714f6a3dedb5274022789d0543cab24d3561a34e31d88fcd9b2ca5",
          "sha1": "2edd18b67d5c3aae48e72b58c135fdcde049fa43",
          "md5": "0af6f2ef79078f1819963ff206a08713"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-v0.1.0.aar",
          "url": "abcmpc-v0.1.0.aar",
          "size": 18696378,
          "sha512": "c801601ad78159901507868a467e310da9ea4cf377f2ed920c21dd6bd13907866dc150807524541cb8a17e80573cb266d9a6e0df1aeff87ab3bfce29b6b89566",
          "sha256": "8bf9e9843c714f6a3dedb5274022789d0543cab24d3561a34e31d88fcd9b2ca5",
          "sha1": "2edd18b67d5c3aae48e72b58c135fdcde049fa43",
          "md5": "0af6f2ef79078f1819963ff206a08713"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "abcmpc-v0.1.0-sources.jar",
          "url": "abcmpc-v0.1.0-sources.jar",
          "size": 4853,
          "sha512": "abc0f33039b5dc789fae5290105d9cabdfabffa4756c8ae9aacb6a187d85e4fe49356b26dc8ba540fda84b3e05debe349bdbd31841979d954c280a43ae97c54a",
          "sha256": "f404bfe31279346099b24dc3569ac55805523d08012dc05f65a11370f9bfeaae",
          "sha1": "98db800c277edce1ee4cebed7345596b6bf1e4d6",
          "md5": "3df86d27eca66eddcdb4939cb705d2b5"
        }
      ]
    }
  ]
}
