{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcmpc",
    "version": "0.1.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.13.aar",
          "url": "abcmpc-0.1.13.aar",
          "size": 19508506,
          "sha512": "0fbc2cb9272ee0b0a0f21b5573a277e663b80d4135f5c6c422e2dd1cfd3ce19236bf9fea02a67dce13a64e3d8c00748e12b41f9c39b640ef1842ddbbb93077f7",
          "sha256": "58199c69d8bf6e65866c29b1e211acaf6d87315a3cbe47027f8b08d445a99aae",
          "sha1": "0b659bf647e6fa12695730fcdc35756f39e04389",
          "md5": "70e13e8410afd9c4e93ee01c246667a4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.13.aar",
          "url": "abcmpc-0.1.13.aar",
          "size": 19508506,
          "sha512": "0fbc2cb9272ee0b0a0f21b5573a277e663b80d4135f5c6c422e2dd1cfd3ce19236bf9fea02a67dce13a64e3d8c00748e12b41f9c39b640ef1842ddbbb93077f7",
          "sha256": "58199c69d8bf6e65866c29b1e211acaf6d87315a3cbe47027f8b08d445a99aae",
          "sha1": "0b659bf647e6fa12695730fcdc35756f39e04389",
          "md5": "70e13e8410afd9c4e93ee01c246667a4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "abcmpc-0.1.13-sources.jar",
          "url": "abcmpc-0.1.13-sources.jar",
          "size": 5325,
          "sha512": "a37e5a7c75261f5f41db5f3fec46471e11ec31f710478abef686ea3a650ccacb9a5b3c6d89c704d1665731c7ddb14c2f4861433742936c42d9ddc98e310f507d",
          "sha256": "7d9e5cd55c1ad6aeec6fab1c14bcb04815449c5a7d9857e7f767d9413ac8991e",
          "sha1": "0c08992a752b3f07eefeca2414c92634b0c7d3fb",
          "md5": "c4168b5d36b4d26548266e84db90068d"
        }
      ]
    }
  ]
}
