{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcmpc",
    "version": "0.1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.18.aar",
          "url": "abcmpc-0.1.18.aar",
          "size": 20237336,
          "sha512": "202972b5dcbd9b60eca59753c8f9e294d588bd140e188b0ba87ad841458d3905100fec53285576f7fc3ff9f777250625e6382379db9437cf080839df08a73da1",
          "sha256": "173a543f1753c14a603ac04721308347227cd7b76179d6f89ee94b64ec8a134a",
          "sha1": "f7b9ca2cfe34e848835aac156b96f8580550a952",
          "md5": "eb3ca14264cb5acd312d1a4d6a70f4a5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.18.aar",
          "url": "abcmpc-0.1.18.aar",
          "size": 20237336,
          "sha512": "202972b5dcbd9b60eca59753c8f9e294d588bd140e188b0ba87ad841458d3905100fec53285576f7fc3ff9f777250625e6382379db9437cf080839df08a73da1",
          "sha256": "173a543f1753c14a603ac04721308347227cd7b76179d6f89ee94b64ec8a134a",
          "sha1": "f7b9ca2cfe34e848835aac156b96f8580550a952",
          "md5": "eb3ca14264cb5acd312d1a4d6a70f4a5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "abcmpc-0.1.18-sources.jar",
          "url": "abcmpc-0.1.18-sources.jar",
          "size": 6403,
          "sha512": "ddab8f8b3d21b4d9e6e2128917cab644f12c2201f1669b2d8c471c00b3177e64d6fe33cfa94325f1d22faa47e116ed76d1180a205a4f13464012b74f714392de",
          "sha256": "60ff5f50a9d258189dd23d4bf5567c43688fea213dc17893cfff353bbe6cadd6",
          "sha1": "218d0bb89dd134cd2deeb631958696d7539d805c",
          "md5": "2b575c06e38e16f6a7ac6eb1af9af1e1"
        }
      ]
    }
  ]
}
