{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcmpc",
    "version": "0.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.11.aar",
          "url": "abcmpc-0.1.11.aar",
          "size": 19507883,
          "sha512": "6cf39fad303687498a2736bd82bb37b81877eddefe8d273a7acc3a6a0097383c2ccc938eed646b68271a6e1ec2d7475ea0158bb3507a3ccfd4ed7c17987892c5",
          "sha256": "0a8eb2e7db562fe7fa5699d27f11073db77b25824a9466635fdf7cd5216ab2e0",
          "sha1": "c6a7915466da8a460126844d285b2b496c77d863",
          "md5": "28ec5992c651625cbe7b1ff44e197681"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.11.aar",
          "url": "abcmpc-0.1.11.aar",
          "size": 19507883,
          "sha512": "6cf39fad303687498a2736bd82bb37b81877eddefe8d273a7acc3a6a0097383c2ccc938eed646b68271a6e1ec2d7475ea0158bb3507a3ccfd4ed7c17987892c5",
          "sha256": "0a8eb2e7db562fe7fa5699d27f11073db77b25824a9466635fdf7cd5216ab2e0",
          "sha1": "c6a7915466da8a460126844d285b2b496c77d863",
          "md5": "28ec5992c651625cbe7b1ff44e197681"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "abcmpc-0.1.11-sources.jar",
          "url": "abcmpc-0.1.11-sources.jar",
          "size": 5371,
          "sha512": "3f14ec87be7ed2c4f87974f2a08eec379fbe2f74440381455f9e0fb94b6103bcd8fedfb4b567ca1cf242c632f6ceb4d22610dc1556f8341ded8e2b8832997345",
          "sha256": "fd91c932e9d36ee905d775edb6492b8a66b4b224b2d271b2c457e3e0e01fb35e",
          "sha1": "b64d9f8069774b165588dfbe84be34b6b0ead49e",
          "md5": "484068807c509ae180608d891d16081f"
        }
      ]
    }
  ]
}
