{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcmpc",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.8.aar",
          "url": "abcmpc-0.1.8.aar",
          "size": 19383822,
          "sha512": "aae31e9e4f74638e13269e53164ecb63f538d26c0d3e7f510c2c9f944ea91a403a73076dcaf54391000c9ea3a68b72241972a464656f2285bc053e76a80cd741",
          "sha256": "3a1dc65edf203ecee864b1f2ceb0b75efbf0d703f0942aa73982bd50bcf788e7",
          "sha1": "0a045715848474447ba28dd8c82c17e92fa55453",
          "md5": "f85e92be4de27fa4f2f556b29d263da1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.8.aar",
          "url": "abcmpc-0.1.8.aar",
          "size": 19383822,
          "sha512": "aae31e9e4f74638e13269e53164ecb63f538d26c0d3e7f510c2c9f944ea91a403a73076dcaf54391000c9ea3a68b72241972a464656f2285bc053e76a80cd741",
          "sha256": "3a1dc65edf203ecee864b1f2ceb0b75efbf0d703f0942aa73982bd50bcf788e7",
          "sha1": "0a045715848474447ba28dd8c82c17e92fa55453",
          "md5": "f85e92be4de27fa4f2f556b29d263da1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "abcmpc-0.1.8-sources.jar",
          "url": "abcmpc-0.1.8-sources.jar",
          "size": 5359,
          "sha512": "074fb90a8e647336d6f1ddd0bc332fca68bd1b1549bfcbb780e541a508eb000bfbcd2433c725013b64da314b64a4b2ec078c865a9af6f261e2e0f1ac874a879b",
          "sha256": "cd59cdae78bd3b1e8569b2eba29b1a4fb65d887f2c70f27d169eb13a2eca5171",
          "sha1": "8204c94f18f789e2339c17467d411ce9c31cc9d8",
          "md5": "f298ff730a137e18c0a636939068bbea"
        }
      ]
    }
  ]
}
