{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcmpc",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.6.aar",
          "url": "abcmpc-0.1.6.aar",
          "size": 18707847,
          "sha512": "a038d3656d315aa1df932807aed128dbe7db0d0c6685bed7097041a53ec44063d9e571e8649d0396fc7faba003cf168696dd665aca087d4703b2cded9b014e93",
          "sha256": "5426c2f2a84cf4e6472dbec67bd6f61fe65a7bb0e945d625ea258eced6d13566",
          "sha1": "a18728a57416e00d056210e07ff554b678a2fd60",
          "md5": "0ea22d903523c3c0283e4312a2e2be3d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.6.aar",
          "url": "abcmpc-0.1.6.aar",
          "size": 18707847,
          "sha512": "a038d3656d315aa1df932807aed128dbe7db0d0c6685bed7097041a53ec44063d9e571e8649d0396fc7faba003cf168696dd665aca087d4703b2cded9b014e93",
          "sha256": "5426c2f2a84cf4e6472dbec67bd6f61fe65a7bb0e945d625ea258eced6d13566",
          "sha1": "a18728a57416e00d056210e07ff554b678a2fd60",
          "md5": "0ea22d903523c3c0283e4312a2e2be3d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "abcmpc-0.1.6-sources.jar",
          "url": "abcmpc-0.1.6-sources.jar",
          "size": 4853,
          "sha512": "abc0f33039b5dc789fae5290105d9cabdfabffa4756c8ae9aacb6a187d85e4fe49356b26dc8ba540fda84b3e05debe349bdbd31841979d954c280a43ae97c54a",
          "sha256": "f404bfe31279346099b24dc3569ac55805523d08012dc05f65a11370f9bfeaae",
          "sha1": "98db800c277edce1ee4cebed7345596b6bf1e4d6",
          "md5": "3df86d27eca66eddcdb4939cb705d2b5"
        }
      ]
    }
  ]
}
