{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcmpc",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.7.aar",
          "url": "abcmpc-0.1.7.aar",
          "size": 18896719,
          "sha512": "385b561eb823390a43beee656924388b9d399bc999cce223b67652e48e9dbcc855909a19349b0c1871f615c99638acc1e5a63db25873e37eb16f1172b5789544",
          "sha256": "48478f1f55795f08ac635943bdb64530c74d448fac35b34d9d66b3d547be3f49",
          "sha1": "9e5707041eebcd87eb56d834748d9d89d5d584b8",
          "md5": "e166958816405fd1f41e44e87d2d0e0a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.7.aar",
          "url": "abcmpc-0.1.7.aar",
          "size": 18896719,
          "sha512": "385b561eb823390a43beee656924388b9d399bc999cce223b67652e48e9dbcc855909a19349b0c1871f615c99638acc1e5a63db25873e37eb16f1172b5789544",
          "sha256": "48478f1f55795f08ac635943bdb64530c74d448fac35b34d9d66b3d547be3f49",
          "sha1": "9e5707041eebcd87eb56d834748d9d89d5d584b8",
          "md5": "e166958816405fd1f41e44e87d2d0e0a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "abcmpc-0.1.7-sources.jar",
          "url": "abcmpc-0.1.7-sources.jar",
          "size": 4853,
          "sha512": "abc0f33039b5dc789fae5290105d9cabdfabffa4756c8ae9aacb6a187d85e4fe49356b26dc8ba540fda84b3e05debe349bdbd31841979d954c280a43ae97c54a",
          "sha256": "f404bfe31279346099b24dc3569ac55805523d08012dc05f65a11370f9bfeaae",
          "sha1": "98db800c277edce1ee4cebed7345596b6bf1e4d6",
          "md5": "3df86d27eca66eddcdb4939cb705d2b5"
        }
      ]
    }
  ]
}
