{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcmpc",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.5.aar",
          "url": "abcmpc-0.1.5.aar",
          "size": 18696554,
          "sha512": "70439fe2c4074700ad5645decc505fa52919f4fe25a5ebcff93add245c650e184c8140b8d89f6b7e65023f263d87024d487e9fd04dc2dff7cf2ecc8228ba8a5a",
          "sha256": "d62e4b42e81c6894bf5bb2067f67e697ec98d9b9e148d048c453f537baccc596",
          "sha1": "e23f1f7142401993719756012bae25aa141e784b",
          "md5": "05574bd7c00acca3a08bb323126953d9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.5.aar",
          "url": "abcmpc-0.1.5.aar",
          "size": 18696554,
          "sha512": "70439fe2c4074700ad5645decc505fa52919f4fe25a5ebcff93add245c650e184c8140b8d89f6b7e65023f263d87024d487e9fd04dc2dff7cf2ecc8228ba8a5a",
          "sha256": "d62e4b42e81c6894bf5bb2067f67e697ec98d9b9e148d048c453f537baccc596",
          "sha1": "e23f1f7142401993719756012bae25aa141e784b",
          "md5": "05574bd7c00acca3a08bb323126953d9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "abcmpc-0.1.5-sources.jar",
          "url": "abcmpc-0.1.5-sources.jar",
          "size": 4853,
          "sha512": "abc0f33039b5dc789fae5290105d9cabdfabffa4756c8ae9aacb6a187d85e4fe49356b26dc8ba540fda84b3e05debe349bdbd31841979d954c280a43ae97c54a",
          "sha256": "f404bfe31279346099b24dc3569ac55805523d08012dc05f65a11370f9bfeaae",
          "sha1": "98db800c277edce1ee4cebed7345596b6bf1e4d6",
          "md5": "3df86d27eca66eddcdb4939cb705d2b5"
        }
      ]
    }
  ]
}
