{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcmpc",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.10.aar",
          "url": "abcmpc-0.1.10.aar",
          "size": 19386171,
          "sha512": "0e971eb98d64855c1acdb9b0bb6facdae36b13a4b548299641bf411fbd13c2e0f7bb7a987f53190fc3bf813734730dc03500a420081a84d7f4d2b3b50151684e",
          "sha256": "8f112ed9c4b54820b7047f49de2d1c47c91b2d1710e71c4814c9ba7e15906fd1",
          "sha1": "82ee109d5856b3b3e696f09a9d874f93ce64c7cb",
          "md5": "5c89819727dd2652e5f78cb985b28d92"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.10.aar",
          "url": "abcmpc-0.1.10.aar",
          "size": 19386171,
          "sha512": "0e971eb98d64855c1acdb9b0bb6facdae36b13a4b548299641bf411fbd13c2e0f7bb7a987f53190fc3bf813734730dc03500a420081a84d7f4d2b3b50151684e",
          "sha256": "8f112ed9c4b54820b7047f49de2d1c47c91b2d1710e71c4814c9ba7e15906fd1",
          "sha1": "82ee109d5856b3b3e696f09a9d874f93ce64c7cb",
          "md5": "5c89819727dd2652e5f78cb985b28d92"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "abcmpc-0.1.10-sources.jar",
          "url": "abcmpc-0.1.10-sources.jar",
          "size": 5371,
          "sha512": "3f14ec87be7ed2c4f87974f2a08eec379fbe2f74440381455f9e0fb94b6103bcd8fedfb4b567ca1cf242c632f6ceb4d22610dc1556f8341ded8e2b8832997345",
          "sha256": "fd91c932e9d36ee905d775edb6492b8a66b4b224b2d271b2c457e3e0e01fb35e",
          "sha1": "b64d9f8069774b165588dfbe84be34b6b0ead49e",
          "md5": "484068807c509ae180608d891d16081f"
        }
      ]
    }
  ]
}
