{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcmpc",
    "version": "0.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.12.aar",
          "url": "abcmpc-0.1.12.aar",
          "size": 19508302,
          "sha512": "3a5c9c4a750c4f518b1592130f138d889559d3f1a134c0607ede885cf4ec56320c4f3236dd7637150ad84bb2650be8c26e36333073ab87e5975009c23e324c2b",
          "sha256": "2d4834f20255beb31b25b2e53df6d0527eff741073deba959e7f7700d97c8d49",
          "sha1": "5b01c5a89f2c8f91fb00e308f5d92e6c70715b31",
          "md5": "0468408889fff2820f88277e957d2c91"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcmpc-0.1.12.aar",
          "url": "abcmpc-0.1.12.aar",
          "size": 19508302,
          "sha512": "3a5c9c4a750c4f518b1592130f138d889559d3f1a134c0607ede885cf4ec56320c4f3236dd7637150ad84bb2650be8c26e36333073ab87e5975009c23e324c2b",
          "sha256": "2d4834f20255beb31b25b2e53df6d0527eff741073deba959e7f7700d97c8d49",
          "sha1": "5b01c5a89f2c8f91fb00e308f5d92e6c70715b31",
          "md5": "0468408889fff2820f88277e957d2c91"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "abcmpc-0.1.12-sources.jar",
          "url": "abcmpc-0.1.12-sources.jar",
          "size": 5325,
          "sha512": "a37e5a7c75261f5f41db5f3fec46471e11ec31f710478abef686ea3a650ccacb9a5b3c6d89c704d1665731c7ddb14c2f4861433742936c42d9ddc98e310f507d",
          "sha256": "7d9e5cd55c1ad6aeec6fab1c14bcb04815449c5a7d9857e7f767d9413ac8991e",
          "sha1": "0c08992a752b3f07eefeca2414c92634b0c7d3fb",
          "md5": "c4168b5d36b4d26548266e84db90068d"
        }
      ]
    }
  ]
}
